// <auto-generated>
// tools/gen_csharp_phrases.py가 voice_lines/urgent_en.yaml에서 생성.
// 손으로 고치지 말 것 — 멘트는 YAML을 고치고 재생성한다.
// </auto-generated>
using System.Collections.Generic;

namespace TeamRadio56.Core.Logic
{
    /// <summary>멘트 풀 항목 — 풀 키 × 톤의 변형 목록.</summary>
    public sealed class PhraseSet
    {
        public string Pool;
        public string Tone;
        public string[] Lines;
    }

    /// <summary>사전 생성 멘트 풀 데이터 — YAML 파일 순서 그대로.</summary>
    public static class PhraseLines
    {
        public static readonly PhraseSet[] All =
        {
            new PhraseSet
            {
                Pool = "traffic_approach",
                Tone = "casual",
                Lines = new[]
                {
                    "{cls} behind, {gap}.",
                    "{cls} closing, {gap}.",
                    "{cls} in {gap}. Hold your line.",
                    "{cls}, {gap} back. Stay on it.",
                    "Traffic. {cls}, {gap}.",
                    "{cls} coming, {gap} out. Let him by on the straight.",
                    "Heads up, {cls} in {gap}.",
                    "{cls} through in {gap}. Line as normal.",
                    "{cls} traffic behind, {gap}.",
                    "One {cls}, {gap} back.",
                },
            },
            new PhraseSet
            {
                Pool = "traffic_approach",
                Tone = "urgent",
                Lines = new[]
                {
                    "Traffic! {cls}, {gap}.",
                    "{cls} closing fast, {gap}.",
                    "{cls}, {gap} out. Mirrors.",
                    "Faster traffic, {cls} in {gap}.",
                    "{cls} {gap} back. Stay on line.",
                    "{cls} coming, {gap}!",
                    "Mirror check. {cls}, {gap}.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside",
                Tone = "urgent",
                Lines = new[]
                {
                    "Car alongside!",
                    "He's alongside!",
                    "Side by side. Leave room.",
                    "Car with you. Hold your line.",
                    "Alongside, no contact!",
                    "He's there, don't squeeze.",
                    "Alongside. Leave a car width.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_left",
                Tone = "urgent",
                Lines = new[]
                {
                    "Car left!",
                    "Left side!",
                    "Left left!",
                    "Car left, careful!",
                    "He's on your left, don't squeeze!",
                    "Left. Leave room.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_right",
                Tone = "urgent",
                Lines = new[]
                {
                    "Car right!",
                    "Right side!",
                    "Right right!",
                    "Car right, careful!",
                    "He's on your right, don't squeeze!",
                    "Right. Leave room.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_both",
                Tone = "urgent",
                Lines = new[]
                {
                    "Cars both sides!",
                    "Both sides!",
                    "Three wide, you're the meat!",
                    "Both sides, no room!",
                },
            },
            new PhraseSet
            {
                Pool = "side_clear",
                Tone = "casual",
                Lines = new[]
                {
                    "Clear {side}.",
                    "{side} is clear.",
                    "Clear {side}, use it.",
                },
            },
            new PhraseSet
            {
                Pool = "nearby_behind",
                Tone = "casual",
                Lines = new[]
                {
                    "Car behind.",
                    "One behind. Stay calm.",
                    "Car closing behind. Hold your line.",
                    "He's there. Keep it consistent.",
                    "{cls} right behind.",
                    "Car behind. Braking points consistent.",
                },
            },
            new PhraseSet
            {
                Pool = "nearby_behind",
                Tone = "urgent",
                Lines = new[]
                {
                    "He's on you!",
                    "Car right behind. Defend once, no more.",
                    "Right behind you! Your line.",
                    "He's there. Keep it clean.",
                    "{cls} right behind!",
                    "Pressure behind. Track position first.",
                },
            },
            new PhraseSet
            {
                Pool = "pass_complete",
                Tone = "casual",
                Lines = new[]
                {
                    "He's through. Back to your line.",
                    "Clear. Back on line.",
                    "He's by. Pace back up.",
                    "Through. Find your rhythm.",
                    "Clear now. Normal line.",
                    "Gone. Back to your race.",
                    "He's past, ahead is clear.",
                },
            },
            new PhraseSet
            {
                Pool = "dropped",
                Tone = "casual",
                Lines = new[]
                {
                    "He's dropped. Keep pace.",
                    "Gap's opening. Well held.",
                    "He's gone backwards. Manage from here.",
                    "Shaken him off.",
                    "Clear behind. Your pace now.",
                },
            },
            new PhraseSet
            {
                Pool = "backmarker_ahead",
                Tone = "casual",
                Lines = new[]
                {
                    "Backmarker ahead, {cls}. Easy does it.",
                    "Backmarker up ahead. Take it clean.",
                    "{cls} ahead is a backmarker. He'll have blue flags.",
                    "Backmarker. Pick your moment, one move.",
                    "Car ahead is a lap down. Not a fight.",
                    "Backmarker traffic. Give it margin.",
                },
            },
            new PhraseSet
            {
                Pool = "backmarker_ahead",
                Tone = "urgent",
                Lines = new[]
                {
                    "Backmarker ahead! Keep your distance.",
                    "Backmarker, stay calm.",
                    "Backmarker ahead. One clean move.",
                },
            },
            new PhraseSet
            {
                Pool = "blue_flag",
                Tone = "casual",
                Lines = new[]
                {
                    "Blue flag. Let him by on the straight.",
                    "Blues for you. Hold your line.",
                    "Blue flag. Keep your pace, let him through.",
                    "Blue. Don't race him, let him go.",
                    "Blue flag. Minimum time loss.",
                },
            },
            new PhraseSet
            {
                Pool = "blue_flag",
                Tone = "urgent",
                Lines = new[]
                {
                    "Blue blue! Let him through.",
                    "Blue flag! Hold line, yield on the straight.",
                    "Blues! Keep it clean, let him by.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_warning",
                Tone = "casual",
                Lines = new[]
                {
                    "Fuel, {fuel_laps} laps.",
                    "Fuel check. {fuel_laps} laps.",
                    "Fuel {fuel_laps} laps. Let's plan the stop.",
                    "{fuel_laps} laps in the tank.",
                    "Fuel {fuel_laps} laps. Window's open.",
                    "Fuel {fuel_laps} laps. Standing by.",
                    "{fuel_laps} laps of fuel. Think about saving.",
                    "Fuel {fuel_laps} laps. Lift and coast.",
                    "Fuel stop in {fuel_laps}. Keep it in mind.",
                    "Fuel {fuel_laps} laps. We'll call it with tyres.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_warning",
                Tone = "urgent",
                Lines = new[]
                {
                    "Fuel {fuel_laps} laps! Start saving.",
                    "Fuel is tight. {fuel_laps} laps.",
                    "Fuel {fuel_laps} laps. Ease off the fights.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_critical",
                Tone = "urgent",
                Lines = new[]
                {
                    "Fuel critical. {fuel_laps} laps.",
                    "Fuel critical. Box within {fuel_laps}.",
                    "Fuel {fuel_laps} laps. Full save now.",
                    "Running dry. {fuel_laps} laps max.",
                    "On fumes. Box within {fuel_laps} laps.",
                    "Critical. Fuel {fuel_laps} laps.",
                    "{fuel_laps} laps, that's all we have. Save fuel.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_call",
                Tone = "casual",
                Lines = new[]
                {
                    "Box box, box box.",
                    "Box box. This lap.",
                    "Box call. Pit this lap.",
                    "Box this lap.",
                    "Pitting this lap. Box box.",
                    "Box box. Crew is ready.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_call",
                Tone = "urgent",
                Lines = new[]
                {
                    "Box box! This lap!",
                    "Come in, box box!",
                    "Window closing. Box this lap.",
                    "Box box. Mind the limiter.",
                },
            },
            new PhraseSet
            {
                Pool = "damage",
                Tone = "urgent",
                Lines = new[]
                {
                    "Contact confirmed. Checking data now.",
                    "Impact. Checking wheels and pressures.",
                    "Possible damage. We're on it.",
                    "Big hit. Report coming shortly.",
                    "Contact. Checking pressures.",
                    "Impact. Keep your pace, checking.",
                    "Impact registered. Give me a few seconds.",
                    "Checking damage. Pace as normal.",
                    "Contact. Checking aero.",
                    "Impact logged. We'll call if there's a problem.",
                },
            },
            new PhraseSet
            {
                Pool = "penalty",
                Tone = "casual",
                Lines = new[]
                {
                    "Penalty. Checking the details.",
                    "Penalty. I'll time the stop for it.",
                    "Penalty from race control.",
                    "We have a penalty. Stay calm.",
                    "Penalty. We'll serve it with the next stop.",
                    "One penalty. Recoverable.",
                    "Penalty confirmed. Keep your pace.",
                    "One penalty. Recalculating strategy.",
                },
            },
            new PhraseSet
            {
                Pool = "race_start",
                Tone = "urgent",
                Lines = new[]
                {
                    "Green green green!",
                    "Green flag!",
                    "We're racing. Careful into turn one.",
                    "Green! Clean start.",
                    "Lights out. Stay calm.",
                    "Green. Survive lap one.",
                },
            },
            new PhraseSet
            {
                Pool = "fcy_start",
                Tone = "urgent",
                Lines = new[]
                {
                    "Full course yellow! Slow down.",
                    "FCY. Eighty kph, no overtaking.",
                    "Safety car deployed. No overtaking.",
                    "Full course yellow. Strategy time.",
                    "FCY! Down to eighty.",
                    "Yellow all round. No passing.",
                },
            },
            new PhraseSet
            {
                Pool = "fcy_pit_open",
                Tone = "urgent",
                Lines = new[]
                {
                    "Pits open! Free stop.",
                    "FCY pit open. Box box.",
                    "Pits are open. Box.",
                    "In in in! Costs us nothing.",
                    "Open. Box box.",
                },
            },
            new PhraseSet
            {
                Pool = "green_flag",
                Tone = "urgent",
                Lines = new[]
                {
                    "Green green! Restart.",
                    "Restart! Focus.",
                    "Green. Racing again.",
                    "Restart green. Mind the tyre temps.",
                    "Green! Use the restart.",
                },
            },
            new PhraseSet
            {
                Pool = "race_end",
                Tone = "casual",
                Lines = new[]
                {
                    "Checkered flag! P{place} in class. Good job.",
                    "That's the flag. P{place}.",
                    "It's done. P{place} in class.",
                    "Checkered. P{place}. I'll put the debrief together.",
                    "Finish. P{place}. Well done.",
                },
            },
            new PhraseSet
            {
                Pool = "position_up",
                Tone = "casual",
                Lines = new[]
                {
                    "P{place} in class. Up one.",
                    "P{place}. Nice.",
                    "P{place}. Keep the rhythm.",
                    "Position up. P{place}.",
                },
            },
            new PhraseSet
            {
                Pool = "position_down",
                Tone = "casual",
                Lines = new[]
                {
                    "P{place} now. We'll take it back.",
                    "P{place}. One lap at a time.",
                    "P{place}. The pace is there, chances will come.",
                    "Lost one. P{place}.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_limiter",
                Tone = "urgent",
                Lines = new[]
                {
                    "Limiter! Limiter!",
                    "Pit speed! Limiter!",
                    "Too fast. Limiter!",
                    "Limiter's off!",
                    "Pit lane speed! Limiter!",
                },
            },
        };
    }
}
