// <auto-generated>
// tools/gen_csharp_phrases.py가 voice_lines/*.yaml에서 생성.
// 손으로 고치지 말 것 — 멘트는 YAML을 고치고 재생성한다.
// </auto-generated>
using System.Collections.Generic;

namespace TeamRadio56.Core.Logic
{
    /// <summary>멘트 풀 항목 — 풀 키 × 톤의 변형 목록.</summary>
    public sealed class PhraseSet
    {
        public string Pool;
        public string Tone;
        public string[] Lines;
    }

    /// <summary>사전 생성 멘트 풀 데이터 — YAML 파일 순서 그대로.</summary>
    public static class PhraseLines
    {
        public static readonly PhraseSet[] All =
        {
            new PhraseSet
            {
                Pool = "traffic_approach",
                Tone = "casual",
                Lines = new[]
                {
                    "{cls} behind, {gap}.",
                    "{cls} closing, {gap}.",
                    "{cls} in {gap}. Hold your line.",
                    "{cls}, {gap} back. Stay on it.",
                    "Traffic. {cls}, {gap}.",
                    "{cls} coming, {gap} out. Let him by on the straight.",
                    "Heads up, {cls} in {gap}.",
                    "{cls} through in {gap}. Line as normal.",
                    "{cls} traffic behind, {gap}.",
                    "One {cls}, {gap} back.",
                },
            },
            new PhraseSet
            {
                Pool = "traffic_approach",
                Tone = "urgent",
                Lines = new[]
                {
                    "Traffic! {cls}, {gap}.",
                    "{cls} closing fast, {gap}.",
                    "{cls}, {gap} out. Mirrors.",
                    "Faster traffic, {cls} in {gap}.",
                    "{cls} {gap} back. Stay on line.",
                    "{cls} coming, {gap}!",
                    "Mirror check. {cls}, {gap}.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside",
                Tone = "urgent",
                Lines = new[]
                {
                    "Car alongside!",
                    "He's alongside!",
                    "Side by side. Leave room.",
                    "Car with you. Hold your line.",
                    "Alongside, no contact!",
                    "He's there, don't squeeze.",
                    "Alongside. Leave a car width.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_left",
                Tone = "urgent",
                Lines = new[]
                {
                    "Car left!",
                    "Left side!",
                    "Left left!",
                    "Car left, careful!",
                    "He's on your left, don't squeeze!",
                    "Left. Leave room.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_right",
                Tone = "urgent",
                Lines = new[]
                {
                    "Car right!",
                    "Right side!",
                    "Right right!",
                    "Car right, careful!",
                    "He's on your right, don't squeeze!",
                    "Right. Leave room.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_both",
                Tone = "urgent",
                Lines = new[]
                {
                    "Cars both sides!",
                    "Both sides!",
                    "Three wide, you're the meat!",
                    "Both sides, no room!",
                },
            },
            new PhraseSet
            {
                Pool = "side_clear",
                Tone = "casual",
                Lines = new[]
                {
                    "Clear {side}.",
                    "{side} is clear.",
                    "Clear {side}, use it.",
                },
            },
            new PhraseSet
            {
                Pool = "nearby_behind",
                Tone = "casual",
                Lines = new[]
                {
                    "Car behind.",
                    "One behind. Stay calm.",
                    "Car closing behind. Hold your line.",
                    "He's there. Keep it consistent.",
                    "{cls} right behind.",
                    "Car behind. Braking points consistent.",
                },
            },
            new PhraseSet
            {
                Pool = "nearby_behind",
                Tone = "urgent",
                Lines = new[]
                {
                    "He's on you!",
                    "Car right behind. Defend once, no more.",
                    "Right behind you! Your line.",
                    "He's there. Keep it clean.",
                    "{cls} right behind!",
                    "Pressure behind. Track position first.",
                },
            },
            new PhraseSet
            {
                Pool = "pass_complete",
                Tone = "casual",
                Lines = new[]
                {
                    "He's through. Back to your line.",
                    "Clear. Back on line.",
                    "He's by. Pace back up.",
                    "Through. Find your rhythm.",
                    "Clear now. Normal line.",
                    "Gone. Back to your race.",
                    "He's past, ahead is clear.",
                },
            },
            new PhraseSet
            {
                Pool = "dropped",
                Tone = "casual",
                Lines = new[]
                {
                    "He's dropped. Keep pace.",
                    "Gap's opening. Well held.",
                    "He's gone backwards. Manage from here.",
                    "Shaken him off.",
                    "Clear behind. Your pace now.",
                },
            },
            new PhraseSet
            {
                Pool = "backmarker_ahead",
                Tone = "casual",
                Lines = new[]
                {
                    "Backmarker ahead, {cls}. Easy does it.",
                    "Backmarker up ahead. Take it clean.",
                    "{cls} ahead is a backmarker. He'll have blue flags.",
                    "Backmarker. Pick your moment, one move.",
                    "Car ahead is a lap down. Not a fight.",
                    "Backmarker traffic. Give it margin.",
                },
            },
            new PhraseSet
            {
                Pool = "backmarker_ahead",
                Tone = "urgent",
                Lines = new[]
                {
                    "Backmarker ahead! Keep your distance.",
                    "Backmarker, stay calm.",
                    "Backmarker ahead. One clean move.",
                },
            },
            new PhraseSet
            {
                Pool = "blue_flag",
                Tone = "casual",
                Lines = new[]
                {
                    "Blue flag. Let him by on the straight.",
                    "Blues for you. Hold your line.",
                    "Blue flag. Keep your pace, let him through.",
                    "Blue. Don't race him, let him go.",
                    "Blue flag. Minimum time loss.",
                },
            },
            new PhraseSet
            {
                Pool = "blue_flag",
                Tone = "urgent",
                Lines = new[]
                {
                    "Blue blue! Let him through.",
                    "Blue flag! Hold line, yield on the straight.",
                    "Blues! Keep it clean, let him by.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_warning",
                Tone = "casual",
                Lines = new[]
                {
                    "Fuel, {fuel_laps}.",
                    "Fuel check. {fuel_laps}.",
                    "Fuel {fuel_laps}. Let's plan the stop.",
                    "{fuel_laps} in the tank.",
                    "Fuel {fuel_laps}. Window's open.",
                    "Fuel {fuel_laps}. Standing by.",
                    "{fuel_laps} of fuel. Think about saving.",
                    "Fuel {fuel_laps}. Lift and coast.",
                    "Fuel stop in {fuel_laps}. Keep it in mind.",
                    "Fuel {fuel_laps}. We'll call it with tyres.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_warning",
                Tone = "urgent",
                Lines = new[]
                {
                    "Fuel {fuel_laps}! Start saving.",
                    "Fuel is tight. {fuel_laps}.",
                    "Fuel {fuel_laps}. Ease off the fights.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_critical",
                Tone = "urgent",
                Lines = new[]
                {
                    "Fuel critical. {fuel_laps}.",
                    "Fuel critical. Box within {fuel_laps}.",
                    "Fuel {fuel_laps}. Full save now.",
                    "Running dry. {fuel_laps} max.",
                    "On fumes. Box within {fuel_laps}.",
                    "Critical. Fuel {fuel_laps}.",
                    "{fuel_laps}, that's all we have. Save fuel.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_call",
                Tone = "casual",
                Lines = new[]
                {
                    "Box box, box box.",
                    "Box box. This lap.",
                    "Box call. Pit this lap.",
                    "Box this lap.",
                    "Pitting this lap. Box box.",
                    "Box box. Crew is ready.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_call",
                Tone = "urgent",
                Lines = new[]
                {
                    "Box box! This lap!",
                    "Come in, box box!",
                    "Window closing. Box this lap.",
                    "Box box. Mind the limiter.",
                },
            },
            new PhraseSet
            {
                Pool = "damage",
                Tone = "urgent",
                Lines = new[]
                {
                    "Contact confirmed. Checking data now.",
                    "Impact. Checking wheels and pressures.",
                    "Possible damage. We're on it.",
                    "Big hit. Report coming shortly.",
                    "Contact. Checking pressures.",
                    "Impact. Keep your pace, checking.",
                    "Impact registered. Give me a few seconds.",
                    "Checking damage. Pace as normal.",
                    "Contact. Checking aero.",
                    "Impact logged. We'll call if there's a problem.",
                },
            },
            new PhraseSet
            {
                Pool = "penalty",
                Tone = "casual",
                Lines = new[]
                {
                    "Penalty. Checking the details.",
                    "Penalty. I'll time the stop for it.",
                    "Penalty from race control.",
                    "We have a penalty. Stay calm.",
                    "Penalty. We'll serve it with the next stop.",
                    "One penalty. Recoverable.",
                    "Penalty confirmed. Keep your pace.",
                    "One penalty. Recalculating strategy.",
                },
            },
            new PhraseSet
            {
                Pool = "race_start",
                Tone = "urgent",
                Lines = new[]
                {
                    "Green green green!",
                    "Green flag!",
                    "We're racing. Careful into turn one.",
                    "Green! Clean start.",
                    "Lights out. Stay calm.",
                    "Green. Survive lap one.",
                },
            },
            new PhraseSet
            {
                Pool = "fcy_start",
                Tone = "urgent",
                Lines = new[]
                {
                    "Full course yellow! Slow down.",
                    "FCY. Eighty kph, no overtaking.",
                    "Safety car deployed. No overtaking.",
                    "Full course yellow. Strategy time.",
                    "FCY! Down to eighty.",
                    "Yellow all round. No passing.",
                },
            },
            new PhraseSet
            {
                Pool = "fcy_pit_open",
                Tone = "urgent",
                Lines = new[]
                {
                    "Pits open! Free stop.",
                    "FCY pit open. Box box.",
                    "Pits are open. Box.",
                    "In in in! Costs us nothing.",
                    "Open. Box box.",
                },
            },
            new PhraseSet
            {
                Pool = "green_flag",
                Tone = "urgent",
                Lines = new[]
                {
                    "Green green! Restart.",
                    "Restart! Focus.",
                    "Green. Racing again.",
                    "Restart green. Mind the tyre temps.",
                    "Green! Use the restart.",
                },
            },
            new PhraseSet
            {
                Pool = "race_end",
                Tone = "casual",
                Lines = new[]
                {
                    "Checkered flag! P{place} in class. Good job.",
                    "That's the flag. P{place}.",
                    "It's done. P{place} in class.",
                    "Checkered. P{place}. I'll put the debrief together.",
                    "Finish. P{place}. Well done.",
                },
            },
            new PhraseSet
            {
                Pool = "position_up",
                Tone = "casual",
                Lines = new[]
                {
                    "P{place} in class. Up one.",
                    "P{place}. Nice.",
                    "P{place}. Keep the rhythm.",
                    "Position up. P{place}.",
                },
            },
            new PhraseSet
            {
                Pool = "position_down",
                Tone = "casual",
                Lines = new[]
                {
                    "P{place} now. We'll take it back.",
                    "P{place}. One lap at a time.",
                    "P{place}. The pace is there, chances will come.",
                    "Lost one. P{place}.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_limiter",
                Tone = "urgent",
                Lines = new[]
                {
                    "Limiter! Limiter!",
                    "Pit speed! Limiter!",
                    "Too fast. Limiter!",
                    "Limiter's off!",
                    "Pit lane speed! Limiter!",
                },
            },
        };

        public static readonly PhraseSet[] Ko =
        {
            new PhraseSet
            {
                Pool = "traffic_approach",
                Tone = "casual",
                Lines = new[]
                {
                    "{cls}, {gap}초 뒤.",
                    "{cls} 접근, {gap}초.",
                    "뒤에 {cls}, {gap}초. 라인 유지.",
                    "{cls} {gap}초. 준비.",
                    "{gap}초 뒤 {cls}. 페이스 유지.",
                    "{cls} 트래픽 {gap}초. 직선에서 보내.",
                    "뒤쪽 {cls}, {gap}초.",
                    "{gap}초 후 {cls} 통과. 라인 그대로.",
                    "체크. {cls} {gap}초 뒤.",
                    "{cls} 하나, {gap}초 뒤.",
                    "곧 {cls}. {gap}초.",
                },
            },
            new PhraseSet
            {
                Pool = "traffic_approach",
                Tone = "urgent",
                Lines = new[]
                {
                    "트래픽! {cls} {gap}초.",
                    "{cls} 클로징, {gap}초.",
                    "{cls} 접근, {gap}초. 미러.",
                    "랩 트래픽, {cls} {gap}초.",
                    "{cls} {gap}초. 하던 대로.",
                    "{cls} 온다, {gap}초!",
                    "미러 체크. {cls} {gap}초.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside",
                Tone = "urgent",
                Lines = new[]
                {
                    "옆이야!",
                    "옆에 붙었어!",
                    "나란히. 공간 줘.",
                    "옆에 차. 라인 유지.",
                    "사이드 바이 사이드!",
                    "옆이야, 접촉 조심!",
                    "옆에 있어, 조이지 마.",
                    "옆 차. 한 대 폭.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_left",
                Tone = "urgent",
                Lines = new[]
                {
                    "왼쪽!",
                    "왼쪽에 차!",
                    "왼쪽 나란히!",
                    "카 레프트!",
                    "왼쪽, 조심!",
                    "왼쪽이야, 조이지 마!",
                    "왼쪽. 공간.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_right",
                Tone = "urgent",
                Lines = new[]
                {
                    "오른쪽!",
                    "오른쪽에 차!",
                    "오른쪽 나란히!",
                    "카 라이트!",
                    "오른쪽, 조심!",
                    "오른쪽이야, 조이지 마!",
                    "오른쪽. 공간.",
                },
            },
            new PhraseSet
            {
                Pool = "alongside_both",
                Tone = "urgent",
                Lines = new[]
                {
                    "양쪽에 차!",
                    "양쪽이야!",
                    "쓰리 와이드, 가운데!",
                    "양옆 붙었다. 공간 없어!",
                },
            },
            new PhraseSet
            {
                Pool = "side_clear",
                Tone = "casual",
                Lines = new[]
                {
                    "{side} 클리어.",
                    "{side} 비었어.",
                    "{side} 클리어, 써도 돼.",
                },
            },
            new PhraseSet
            {
                Pool = "nearby_behind",
                Tone = "casual",
                Lines = new[]
                {
                    "뒤 붙었어.",
                    "뒤에 하나. 침착하게.",
                    "뒤차 근접. 라인 유지.",
                    "뒤에 있어. 움직임 일정하게.",
                    "{cls} 뒤에 붙었어.",
                    "뒤에 차. 라인 그대로.",
                    "뒤차 근접. 브레이킹 일정하게.",
                },
            },
            new PhraseSet
            {
                Pool = "nearby_behind",
                Tone = "urgent",
                Lines = new[]
                {
                    "뒤 붙었어!",
                    "뒤차 코앞. 방어는 한 번만.",
                    "바로 뒤야! 라인 지켜.",
                    "붙었어 뒤에. 깔끔하게.",
                    "{cls} 바로 뒤!",
                    "뒤차 근접. 포지션 우선.",
                },
            },
            new PhraseSet
            {
                Pool = "pass_complete",
                Tone = "casual",
                Lines = new[]
                {
                    "지나갔어. 라인 복귀.",
                    "클리어. 니 라인으로.",
                    "보냈어. 페이스 회복.",
                    "지나갔다. 리듬 찾아.",
                    "클리어. 정상 라인.",
                    "갔어. 니 레이스.",
                    "보냈고, 앞 클리어.",
                },
            },
            new PhraseSet
            {
                Pool = "dropped",
                Tone = "casual",
                Lines = new[]
                {
                    "떨어졌어. 페이스 유지.",
                    "갭 벌어졌다. 잘 버텼어.",
                    "뒤차 떨어짐. 관리 모드.",
                    "털어냈어.",
                    "뒤 클리어. 니 페이스로.",
                },
            },
            new PhraseSet
            {
                Pool = "backmarker_ahead",
                Tone = "casual",
                Lines = new[]
                {
                    "앞에 백마커 {cls}. 침착하게.",
                    "전방 백마커. 깔끔하게 처리.",
                    "앞 {cls} 백마커. 블루 받는 중일 거야.",
                    "백마커. 타이밍 봐서 한 번에.",
                    "앞차 랩 다운. 배틀 아님.",
                    "백마커 트래픽. 여유 두고.",
                },
            },
            new PhraseSet
            {
                Pool = "backmarker_ahead",
                Tone = "urgent",
                Lines = new[]
                {
                    "앞 백마커! 거리 두고.",
                    "백마커 조심. 침착하게.",
                    "전방 백마커. 한 번에 처리.",
                },
            },
            new PhraseSet
            {
                Pool = "blue_flag",
                Tone = "casual",
                Lines = new[]
                {
                    "블루 플래그. 직선에서 보내줘.",
                    "블루 떴어. 라인 유지.",
                    "블루. 페이스 지키면서 보내.",
                    "블루. 코너 말고 직선에서.",
                    "블루 플래그. 배틀 아니야, 편하게.",
                    "블루. 타임 로스 최소로.",
                },
            },
            new PhraseSet
            {
                Pool = "blue_flag",
                Tone = "urgent",
                Lines = new[]
                {
                    "블루 블루! 보내줘.",
                    "블루! 라인 유지, 직선 양보.",
                    "블루! 깔끔하게 보내자.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_warning",
                Tone = "casual",
                Lines = new[]
                {
                    "연료 {fuel_laps}랩.",
                    "연료 체크. {fuel_laps}랩.",
                    "연료 {fuel_laps}랩. 피트 계획 잡자.",
                    "탱크에 {fuel_laps}랩.",
                    "퓨얼 {fuel_laps}랩. 윈도우 오픈.",
                    "연료 {fuel_laps}랩. 준비하고 있어.",
                    "{fuel_laps}랩 치 남았어. 세이브 고려.",
                    "연료 {fuel_laps}랩. 리프트 앤 코스트.",
                    "{fuel_laps}랩 뒤 급유. 염두에 둬.",
                    "연료 {fuel_laps}랩. 타이어랑 같이 판단.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_warning",
                Tone = "urgent",
                Lines = new[]
                {
                    "연료 {fuel_laps}랩! 세이브.",
                    "퓨얼 타이트. {fuel_laps}랩.",
                    "연료 {fuel_laps}랩. 배틀 자제.",
                },
            },
            new PhraseSet
            {
                Pool = "fuel_critical",
                Tone = "urgent",
                Lines = new[]
                {
                    "연료 크리티컬. {fuel_laps}랩.",
                    "퓨얼 크리티컬. {fuel_laps}랩 안에 박스.",
                    "연료 {fuel_laps}랩. 풀 세이브.",
                    "탱크 바닥. {fuel_laps}랩 리밋.",
                    "연료 한계. {fuel_laps}랩 안에 박스.",
                    "크리티컬. 연료 {fuel_laps}랩.",
                    "{fuel_laps}랩 마지노선. 세이브.",
                    "연료 {fuel_laps}랩. 세이브 필수.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_call",
                Tone = "casual",
                Lines = new[]
                {
                    "박스 박스, 박스 박스.",
                    "박스 박스. 이번 랩.",
                    "박스 콜. 이번 랩 피트인.",
                    "이번 랩 박스.",
                    "피트인, 이번 랩. 박스 박스.",
                    "박스 박스. 크루 대기 중.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_call",
                Tone = "urgent",
                Lines = new[]
                {
                    "박스 박스! 이번 랩!",
                    "들어와, 박스 박스!",
                    "윈도우 마감. 이번 랩 박스.",
                    "박스 박스. 리미터 잊지 마.",
                },
            },
            new PhraseSet
            {
                Pool = "damage",
                Tone = "urgent",
                Lines = new[]
                {
                    "접촉 확인. 데이터 체크 중.",
                    "임팩트. 휠, 공기압 확인 중.",
                    "데미지 가능성. 보고 있어.",
                    "충격 컸어. 결과 곧 불러줄게.",
                    "접촉. 프레셔 확인 중.",
                    "임팩트. 페이스 유지, 체크 중.",
                    "충격 감지. 몇 초만.",
                    "데미지 체크 중. 페이스 유지.",
                    "접촉 감지. 에어로 확인 중.",
                    "임팩트 로그. 문제면 바로 콜.",
                },
            },
            new PhraseSet
            {
                Pool = "penalty",
                Tone = "casual",
                Lines = new[]
                {
                    "페널티 떴어. 내용 확인 중.",
                    "페널티. 처리 타이밍 잡아줄게.",
                    "스튜어드 콜. 페널티 하나.",
                    "페널티. 침착하게.",
                    "페널티. 다음 피트에 처리하자.",
                    "페널티 하나. 만회 가능.",
                    "페널티 확인. 페이스 유지.",
                    "페널티 하나. 전략 다시 계산 중.",
                },
            },
            new PhraseSet
            {
                Pool = "race_start",
                Tone = "urgent",
                Lines = new[]
                {
                    "그린 그린 그린!",
                    "그린 플래그!",
                    "스타트! 첫 코너 조심.",
                    "그린! 클린 스타트.",
                    "레이스 온. 침착하게.",
                    "그린. 생존 먼저.",
                },
            },
            new PhraseSet
            {
                Pool = "fcy_start",
                Tone = "urgent",
                Lines = new[]
                {
                    "풀코스옐로! 감속.",
                    "FCY. 추월 금지, 델타 유지.",
                    "세이프티카. 감속.",
                    "풀코스옐로. 전략 타임.",
                    "FCY! 델타 맞춰.",
                    "옐로 전 구간. 추월 금지.",
                },
            },
            new PhraseSet
            {
                Pool = "fcy_pit_open",
                Tone = "urgent",
                Lines = new[]
                {
                    "피트 오픈! 공짜 피트야.",
                    "FCY 피트 오픈. 박스 박스.",
                    "피트 열렸어. 박스.",
                    "지금 들어와! 손해 없어.",
                    "오픈. 박스 박스.",
                },
            },
            new PhraseSet
            {
                Pool = "green_flag",
                Tone = "urgent",
                Lines = new[]
                {
                    "그린 그린! 리스타트.",
                    "리스타트! 집중.",
                    "그린. 다시 레이스.",
                    "리스타트 그린. 타이어 온도 체크.",
                    "그린! 리스타트에 기회 있어.",
                },
            },
            new PhraseSet
            {
                Pool = "race_end",
                Tone = "casual",
                Lines = new[]
                {
                    "체커! 클래스 {place}등. 수고했어.",
                    "체커드 플래그. P{place}.",
                    "끝났어. 클래스 P{place}. 좋은 레이스.",
                    "체커. P{place}. 디브리핑 정리할게.",
                    "피니시. P{place}. 고생했어.",
                },
            },
            new PhraseSet
            {
                Pool = "position_up",
                Tone = "casual",
                Lines = new[]
                {
                    "클래스 P{place}. 업.",
                    "P{place}. 좋아.",
                    "P{place}. 흐름 유지.",
                    "포지션 업. 클래스 P{place}.",
                },
            },
            new PhraseSet
            {
                Pool = "position_down",
                Tone = "casual",
                Lines = new[]
                {
                    "클래스 P{place}. 침착하게 되찾자.",
                    "P{place}. 한 랩씩.",
                    "P{place}. 페이스 있으니까 기회 온다.",
                    "한 자리 내줬어. P{place}.",
                },
            },
            new PhraseSet
            {
                Pool = "pit_limiter",
                Tone = "urgent",
                Lines = new[]
                {
                    "리미터! 리미터!",
                    "피트 스피드! 리미터!",
                    "속도 초과. 리미터!",
                    "리미터 안 켜졌어!",
                    "피트레인 속도! 리미터!",
                },
            },
        };

    }
}
