// <auto-generated>
//   tools/gen_csharp_structs.py 가 rf2data.py 에서 생성. 직접 수정하지 말 것.
//   레이아웃 원본: The Iron Wolf, rF2 Shared Memory Map Plugin
//   파이썬 매핑: Tony Whitley, pyRfactor2SharedMemory
// </auto-generated>
using System.Runtime.InteropServices;

namespace TeamRadio56.Core.Telemetry
{
    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2Vec3
    {
        public double x;
        public double y;
        public double z;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2Wheel
    {
        public double mSuspensionDeflection;
        public double mRideHeight;
        public double mSuspForce;
        public double mBrakeTemp;
        public double mBrakePressure;
        public double mRotation;
        public double mLateralPatchVel;
        public double mLongitudinalPatchVel;
        public double mLateralGroundVel;
        public double mLongitudinalGroundVel;
        public double mCamber;
        public double mLateralForce;
        public double mLongitudinalForce;
        public double mTireLoad;
        public double mGripFract;
        public double mPressure;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
        public double[] mTemperature;
        public double mWear;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
        public byte[] mTerrainName;
        public byte mSurfaceType;
        public byte mFlat;
        public byte mDetached;
        public byte mStaticUndeflectedRadius;
        public double mVerticalTireDeflection;
        public double mWheelYLocation;
        public double mToe;
        public double mTireCarcassTemperature;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
        public double[] mTireInnerLayerTemperature;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 24)]
        public byte[] mExpansion;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2VehicleTelemetry
    {
        public int mID;
        public double mDeltaTime;
        public double mElapsedTime;
        public int mLapNumber;
        public double mLapStartET;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 64)]
        public byte[] mVehicleName;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 64)]
        public byte[] mTrackName;
        public rF2Vec3 mPos;
        public rF2Vec3 mLocalVel;
        public rF2Vec3 mLocalAccel;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
        public rF2Vec3[] mOri;
        public rF2Vec3 mLocalRot;
        public rF2Vec3 mLocalRotAccel;
        public int mGear;
        public double mEngineRPM;
        public double mEngineWaterTemp;
        public double mEngineOilTemp;
        public double mClutchRPM;
        public double mUnfilteredThrottle;
        public double mUnfilteredBrake;
        public double mUnfilteredSteering;
        public double mUnfilteredClutch;
        public double mFilteredThrottle;
        public double mFilteredBrake;
        public double mFilteredSteering;
        public double mFilteredClutch;
        public double mSteeringShaftTorque;
        public double mFront3rdDeflection;
        public double mRear3rdDeflection;
        public double mFrontWingHeight;
        public double mFrontRideHeight;
        public double mRearRideHeight;
        public double mDrag;
        public double mFrontDownforce;
        public double mRearDownforce;
        public double mFuel;
        public double mEngineMaxRPM;
        public byte mScheduledStops;
        public byte mOverheating;
        public byte mDetached;
        public byte mHeadlights;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public byte[] mDentSeverity;
        public double mLastImpactET;
        public double mLastImpactMagnitude;
        public rF2Vec3 mLastImpactPos;
        public double mEngineTorque;
        public int mCurrentSector;
        public byte mSpeedLimiter;
        public byte mMaxGears;
        public byte mFrontTireCompoundIndex;
        public byte mRearTireCompoundIndex;
        public double mFuelCapacity;
        public byte mFrontFlapActivated;
        public byte mRearFlapActivated;
        public byte mRearFlapLegalStatus;
        public byte mIgnitionStarter;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 18)]
        public byte[] mFrontTireCompoundName;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 18)]
        public byte[] mRearTireCompoundName;
        public byte mSpeedLimiterAvailable;
        public byte mAntiStallActivated;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 2)]
        public byte[] mUnused;
        public float mVisualSteeringWheelRange;
        public double mRearBrakeBias;
        public double mTurboBoostPressure;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
        public float[] mPhysicsToGraphicsOffset;
        public float mPhysicalSteeringWheelRange;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 152)]
        public byte[] mExpansion;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
        public rF2Wheel[] mWheels;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2ScoringInfo
    {
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 64)]
        public byte[] mTrackName;
        public int mSession;
        public double mCurrentET;
        public double mEndET;
        public int mMaxLaps;
        public double mLapDist;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public byte[] pointer1;
        public int mNumVehicles;
        public byte mGamePhase;
        public byte mYellowFlagState;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
        public byte[] mSectorFlag;
        public byte mStartLight;
        public byte mNumRedLights;
        public byte mInRealtime;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]
        public byte[] mPlayerName;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 64)]
        public byte[] mPlrFileName;
        public double mDarkCloud;
        public double mRaining;
        public double mAmbientTemp;
        public double mTrackTemp;
        public rF2Vec3 mWind;
        public double mMinPathWetness;
        public double mMaxPathWetness;
        public byte mGameMode;
        public byte mIsPasswordProtected;
        public short mServerPort;
        public int mServerPublicIP;
        public int mMaxPlayers;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]
        public byte[] mServerName;
        public float mStartET;
        public double mAvgPathWetness;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 200)]
        public byte[] mExpansion;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 8)]
        public byte[] pointer2;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2VehicleScoring
    {
        public int mID;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]
        public byte[] mDriverName;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 64)]
        public byte[] mVehicleName;
        public short mTotalLaps;
        public byte mSector;
        public byte mFinishStatus;
        public double mLapDist;
        public double mPathLateral;
        public double mTrackEdge;
        public double mBestSector1;
        public double mBestSector2;
        public double mBestLapTime;
        public double mLastSector1;
        public double mLastSector2;
        public double mLastLapTime;
        public double mCurSector1;
        public double mCurSector2;
        public short mNumPitstops;
        public short mNumPenalties;
        public byte mIsPlayer;
        public byte mControl;
        public byte mInPits;
        public byte mPlace;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 32)]
        public byte[] mVehicleClass;
        public double mTimeBehindNext;
        public int mLapsBehindNext;
        public double mTimeBehindLeader;
        public int mLapsBehindLeader;
        public double mLapStartET;
        public rF2Vec3 mPos;
        public rF2Vec3 mLocalVel;
        public rF2Vec3 mLocalAccel;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)]
        public rF2Vec3[] mOri;
        public rF2Vec3 mLocalRot;
        public rF2Vec3 mLocalRotAccel;
        public byte mHeadlights;
        public byte mPitState;
        public byte mServerScored;
        public byte mIndividualPhase;
        public int mQualification;
        public double mTimeIntoLap;
        public double mEstimatedLapTime;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 24)]
        public byte[] mPitGroup;
        public byte mFlag;
        public byte mUnderYellow;
        public byte mCountLapFlag;
        public byte mInGarageStall;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 16)]
        public byte[] mUpgradePack;
        public float mPitLapDist;
        public float mBestLapSector1;
        public float mBestLapSector2;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 48)]
        public byte[] mExpansion;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2PhysicsOptions
    {
        public byte mTractionControl;
        public byte mAntiLockBrakes;
        public byte mStabilityControl;
        public byte mAutoShift;
        public byte mAutoClutch;
        public byte mInvulnerable;
        public byte mOppositeLock;
        public byte mSteeringHelp;
        public byte mBrakingHelp;
        public byte mSpinRecovery;
        public byte mAutoPit;
        public byte mAutoLift;
        public byte mAutoBlip;
        public byte mFuelMult;
        public byte mTireMult;
        public byte mMechFail;
        public byte mAllowPitcrewPush;
        public byte mRepeatShifts;
        public byte mHoldClutch;
        public byte mAutoReverse;
        public byte mAlternateNeutral;
        public byte mAIControl;
        public byte mUnused1;
        public byte mUnused2;
        public float mManualShiftOverrideTime;
        public float mAutoShiftOverrideTime;
        public float mSpeedSensitiveSteering;
        public float mSteerRatioSpeed;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2TrackedDamage
    {
        public double mMaxImpactMagnitude;
        public double mAccumulatedImpactMagnitude;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2VehScoringCapture
    {
        public int mID;
        public byte mPlace;
        public byte mIsPlayer;
        public byte mFinishStatus;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2SessionTransitionCapture
    {
        public byte mGamePhase;
        public int mSession;
        public int mNumScoringVehicles;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)]
        public rF2VehScoringCapture[] mScoringVehicles;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2Telemetry
    {
        public int mVersionUpdateBegin;
        public int mVersionUpdateEnd;
        public int mBytesUpdatedHint;
        public int mNumVehicles;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)]
        public rF2VehicleTelemetry[] mVehicles;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2Scoring
    {
        public int mVersionUpdateBegin;
        public int mVersionUpdateEnd;
        public int mBytesUpdatedHint;
        public rF2ScoringInfo mScoringInfo;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)]
        public rF2VehicleScoring[] mVehicles;
    }

    [StructLayout(LayoutKind.Sequential, Pack = 4)]
    public struct rF2Extended
    {
        public int mVersionUpdateBegin;
        public int mVersionUpdateEnd;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 12)]
        public byte[] mVersion;
        public byte is64bit;
        public rF2PhysicsOptions mPhysics;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 512)]
        public rF2TrackedDamage[] mTrackedDamages;
        public byte mInRealtimeFC;
        public byte mMultimediaThreadStarted;
        public byte mSimulationThreadStarted;
        public byte mSessionStarted;
        public double mTicksSessionStarted;
        public double mTicksSessionEnded;
        public rF2SessionTransitionCapture mSessionTransitionCapture;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)]
        public byte[] mDisplayedMessageUpdateCapture;
        public byte mDirectMemoryAccessEnabled;
        public double mTicksStatusMessageUpdated;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)]
        public byte[] mStatusMessage;
        public double mTicksLastHistoryMessageUpdated;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 128)]
        public byte[] mLastHistoryMessage;
        public float mCurrentPitSpeedLimit;
        public byte mSCRPluginEnabled;
        public int mSCRPluginDoubleFileType;
        public double mTicksLSIPhaseMessageUpdated;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 96)]
        public byte[] mLSIPhaseMessage;
        public double mTicksLSIPitStateMessageUpdated;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 96)]
        public byte[] mLSIPitStateMessage;
        public double mTicksLSIOrderInstructionMessageUpdated;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 96)]
        public byte[] mLSIOrderInstructionMessage;
        public double mTicksLSIRulesInstructionMessageUpdated;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 96)]
        public byte[] mLSIRulesInstructionMessage;
        public int mUnsubscribedBuffersMask;
        public byte mHWControlInputEnabled;
        public byte mWeatherControlInputEnabled;
        public byte mRulesControlInputEnabled;
    }

    /// <summary>ctypes 기준 기대 바이트 크기 — Marshal.SizeOf 와 대조해 레이아웃을 검증한다.</summary>
    public static class RF2Sizes
    {
        public const int rF2Vec3 = 24;
        public const int rF2Wheel = 260;
        public const int rF2VehicleTelemetry = 1888;
        public const int rF2ScoringInfo = 548;
        public const int rF2VehicleScoring = 584;
        public const int rF2PhysicsOptions = 40;
        public const int rF2TrackedDamage = 16;
        public const int rF2VehScoringCapture = 8;
        public const int rF2SessionTransitionCapture = 1036;
        public const int rF2Telemetry = 241680;
        public const int rF2Scoring = 75312;
        public const int rF2Extended = 10152;
    }
}
