"""
rf2data.py(ctypes 정의) → C# 구조체 자동 생성.

C# 포팅 시 구조체를 손으로 옮기면 한 필드만 어긋나도 모든 값이 깨진다.
파이썬 정의를 introspection으로 읽어 C#을 생성해 전사 오류를 없앤다.
생성물에는 ctypes.sizeof로 구한 기대 크기가 상수로 박히고, C# 쪽에서
Marshal.SizeOf와 비교해 런타임에 레이아웃 일치를 검증한다.

사용법:
    python tools/gen_csharp_structs.py
    → simhub/src/TeamRadio56.Core/Telemetry/RF2Data.Generated.cs
"""

import ctypes
import io
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import rf2data as R  # noqa: E402

OUT = os.path.join("simhub", "src", "TeamRadio56.Core", "Telemetry",
                   "RF2Data.Generated.cs")

# 생성 대상 (의존 순서대로 — C#은 순서 무관하지만 가독성 위해 유지)
STRUCTS = [
    "rF2Vec3", "rF2Wheel", "rF2VehicleTelemetry", "rF2ScoringInfo",
    "rF2VehicleScoring", "rF2PhysicsOptions", "rF2TrackedDamage",
    "rF2VehScoringCapture", "rF2SessionTransitionCapture",
    "rF2Telemetry", "rF2Scoring", "rF2Extended",
]

SCALARS = {
    ctypes.c_double: "double",
    ctypes.c_float: "float",
    ctypes.c_int: "int",
    ctypes.c_uint: "uint",
    ctypes.c_short: "short",
    ctypes.c_ushort: "ushort",
    ctypes.c_ubyte: "byte",
    ctypes.c_byte: "sbyte",
    ctypes.c_longlong: "long",
    ctypes.c_ulonglong: "ulong",
    ctypes.c_char: "byte",
}


def cs_type(ctype):
    """ctypes 타입 → (C# 타입명, 배열 길이 or None)."""
    if ctype in SCALARS:
        return SCALARS[ctype], None
    if hasattr(ctype, "_length_") and hasattr(ctype, "_type_"):
        inner, inner_len = cs_type(ctype._type_)
        if inner_len is not None:
            raise NotImplementedError("2차원 배열은 지원하지 않음")
        return inner, ctype._length_
    if issubclass(ctype, ctypes.Structure):
        return ctype.__name__, None
    raise NotImplementedError(f"알 수 없는 타입: {ctype}")


def emit_struct(name):
    st = getattr(R, name)
    out = [f"    [StructLayout(LayoutKind.Sequential, Pack = 4)]",
           f"    public struct {name}",
           "    {"]
    for field, ctype in st._fields_:
        cs, length = cs_type(ctype)
        if length is None:
            out.append(f"        public {cs} {field};")
        else:
            out.append(f"        [MarshalAs(UnmanagedType.ByValArray, "
                       f"SizeConst = {length})]")
            out.append(f"        public {cs}[] {field};")
    out.append("    }")
    return "\n".join(out)


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    parts = ['''// <auto-generated>
//   tools/gen_csharp_structs.py 가 rf2data.py 에서 생성. 직접 수정하지 말 것.
//   레이아웃 원본: The Iron Wolf, rF2 Shared Memory Map Plugin
//   파이썬 매핑: Tony Whitley, pyRfactor2SharedMemory
// </auto-generated>
using System.Runtime.InteropServices;

namespace TeamRadio56.Core.Telemetry
{''']
    for name in STRUCTS:
        parts.append(emit_struct(name))
        parts.append("")

    # 레이아웃 검증용 기대 크기
    sizes = [f"        public const int {n} = {ctypes.sizeof(getattr(R, n))};"
             for n in STRUCTS]
    parts.append("    /// <summary>ctypes 기준 기대 바이트 크기 — "
                 "Marshal.SizeOf 와 대조해 레이아웃을 검증한다.</summary>")
    parts.append("    public static class RF2Sizes\n    {")
    parts.extend(sizes)
    parts.append("    }")
    parts.append("}")

    with io.open(OUT, "w", encoding="utf-8", newline="\r\n") as f:
        f.write("\n".join(parts) + "\n")

    total = sum(len(getattr(R, n)._fields_) for n in STRUCTS)
    print(f"생성 완료: {OUT}")
    print(f"  구조체 {len(STRUCTS)}개, 필드 {total}개")
    for n in ("rF2Telemetry", "rF2Scoring", "rF2Extended"):
        print(f"  {n}: {ctypes.sizeof(getattr(R, n))} bytes")


if __name__ == "__main__":
    main()
