"""
voice_lines/*.yaml → C# 멘트 풀 데이터 자동 생성.

런타임 YAML 파서 의존을 만들지 않기 위해 (gen_csharp_structs.py와 같은
패턴) 데이터를 C# 소스로 굽는다. 멘트를 고치면 다시 실행할 것:

    python tools/gen_csharp_phrases.py

출력: simhub/src/TeamRadio56.Core/Logic/PhraseLines.Generated.cs
"""

from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import yaml  # noqa: E402

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# (yaml, C# 배열 이름) — en은 All, ko는 Ko (PhrasePool이 언어로 고른다)
SRCS = [
    (os.path.join(_ROOT, "voice_lines", "urgent_en.yaml"), "All"),
    (os.path.join(_ROOT, "voice_lines", "urgent_ko.yaml"), "Ko"),
]
DST = os.path.join(_ROOT, "simhub", "src", "TeamRadio56.Core", "Logic",
                   "PhraseLines.Generated.cs")


def cs_str(s: str) -> str:
    out = s.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{out}"'


def main() -> int:
    lines: list[str] = []
    lines.append("// <auto-generated>")
    lines.append("// tools/gen_csharp_phrases.py가 voice_lines/*.yaml에서 생성.")
    lines.append("// 손으로 고치지 말 것 — 멘트는 YAML을 고치고 재생성한다.")
    lines.append("// </auto-generated>")
    lines.append("using System.Collections.Generic;")
    lines.append("")
    lines.append("namespace TeamRadio56.Core.Logic")
    lines.append("{")
    lines.append("    /// <summary>멘트 풀 항목 — 풀 키 × 톤의 변형 목록.</summary>")
    lines.append("    public sealed class PhraseSet")
    lines.append("    {")
    lines.append("        public string Pool;")
    lines.append("        public string Tone;")
    lines.append("        public string[] Lines;")
    lines.append("    }")
    lines.append("")
    lines.append("    /// <summary>사전 생성 멘트 풀 데이터 — YAML 파일 순서 그대로.</summary>")
    lines.append("    public static class PhraseLines")
    lines.append("    {")

    counts = []
    for src, array_name in SRCS:
        with open(src, "r", encoding="utf-8") as f:
            pools = yaml.safe_load(f) or {}
        lines.append(f"        public static readonly PhraseSet[] {array_name} =")
        lines.append("        {")
        total = 0
        for pool_key, entry in pools.items():
            tones = entry if isinstance(entry, dict) else {"casual": entry}
            for tone, phrase_list in tones.items():
                if not phrase_list:
                    continue
                total += len(phrase_list)
                lines.append("            new PhraseSet")
                lines.append("            {")
                lines.append(f"                Pool = {cs_str(pool_key)},")
                lines.append(f"                Tone = {cs_str(tone)},")
                lines.append("                Lines = new[]")
                lines.append("                {")
                for phrase in phrase_list:
                    lines.append(f"                    {cs_str(phrase)},")
                lines.append("                },")
                lines.append("            },")
        lines.append("        };")
        lines.append("")
        counts.append((os.path.basename(src), len(pools), total))

    lines.append("    }")
    lines.append("}")

    with open(DST, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    for name, pool_n, total in counts:
        print(f"생성: {name} → 풀 {pool_n}개, 변형 {total}개")
    return 0


if __name__ == "__main__":
    sys.exit(main())
